//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabXML {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NamesForFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NamesForFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabXML.NamesForFiles", typeof(NamesForFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discipline.
        /// </summary>
        public static string DElement {
            get {
                return ResourceManager.GetString("DElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisciplineId.
        /// </summary>
        public static string DisciplineId {
            get {
                return ResourceManager.GetString("DisciplineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disciplines.
        /// </summary>
        public static string DRoot {
            get {
                return ResourceManager.GetString("DRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disciplines.xml.
        /// </summary>
        public static string DXml {
            get {
                return ResourceManager.GetString("DXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam.
        /// </summary>
        public static string EElement {
            get {
                return ResourceManager.GetString("EElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exams.
        /// </summary>
        public static string ERoot {
            get {
                return ResourceManager.GetString("ERoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exams.xml.
        /// </summary>
        public static string EXml {
            get {
                return ResourceManager.GetString("EXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastName.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LecturerId.
        /// </summary>
        public static string LecturerId {
            get {
                return ResourceManager.GetString("LecturerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        public static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patronymic.
        /// </summary>
        public static string Patronymic {
            get {
                return ResourceManager.GetString("Patronymic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PractitionerId.
        /// </summary>
        public static string PractitionerId {
            get {
                return ResourceManager.GetString("PractitionerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string SElement {
            get {
                return ResourceManager.GetString("SElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semester.
        /// </summary>
        public static string Semester {
            get {
                return ResourceManager.GetString("Semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string SRoot {
            get {
                return ResourceManager.GetString("SRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StudentId.
        /// </summary>
        public static string StudentId {
            get {
                return ResourceManager.GetString("StudentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to students.xml.
        /// </summary>
        public static string SXml {
            get {
                return ResourceManager.GetString("SXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string TElement {
            get {
                return ResourceManager.GetString("TElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teachers.
        /// </summary>
        public static string TRoot {
            get {
                return ResourceManager.GetString("TRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teachers.xml.
        /// </summary>
        public static string TXml {
            get {
                return ResourceManager.GetString("TXml", resourceCulture);
            }
        }
    }
}
